customize: fixing nil issue
2.2.2 :024 > o.object_attachments.first.file.recreate_versions!
NoMethodError: undefined method `headers' for #<String:0x00000007717698>
	from /root/fountain/shared/bundle/ruby/2.2.0/gems/carrierwave-aliyun-0.8.1/lib/carrierwave/storage/aliyun_file.rb:14:in `read'
	from /root/fountain/shared/bundle/ruby/2.2.0/gems/carrierwave-1.0.0/lib/carrierwave/uploader/cache.rb:81:in `sanitized_file'
	from /root/fountain/shared/bundle/ruby/2.2.0/gems/carrierwave-1.0.0/lib/carrierwave/uploader/cache.rb:118:in `cache!'
	from /root/fountain/shared/bundle/ruby/2.2.0/gems/carrierwave-1.0.0/lib/carrierwave/uploader/versions.rb:227:in `recreate_versions!'
	from (irb):24
	from /root/fountain/shared/bundle/ruby/2.2.0/gems/railties-5.0.1/lib/rails/commands/console.rb:65:in `start'
	from /root/fountain/shared/bundle/ruby/2.2.0/gems/railties-5.0.1/lib/rails/commands/console_helper.rb:9:in `start'
	from /root/fountain/shared/bundle/ruby/2.2.0/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /root/fountain/shared/bundle/ruby/2.2.0/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /root/fountain/shared/bundle/ruby/2.2.0/gems/railties-5.0.1/lib/rails/commands.rb:18:in `<top (required)>